var kategoriler = [{
    "arac-turleri" : ["OTOMOBİL","MOTOSİKLET"],
    "markalar": [],
    "modeller": [],
    "yakit-turleri" : [],
    "motor-hacimleri" : [],
    "motor-gucleri" : [],
    "vites-turleri" :[],
    "donanım-ozellikleri":[],
}];

//localStorage.setItem("kategoriler",JSON.stringify(kategoriler));
var kategoriler = JSON.parse(localStorage.getItem("kategoriler"));

var otomobil_list =[
    "Aion",
    "Alfa Romeo",           
    "Anadol",  
    "Arora", 
    "Aston Martin", 
    "Audi", 
    "Bentley", 
    "BMW", 
    "Bugatti", 
    "Buick", 
    "Cadillac", 
    "Chery", 
    "Chevrolet", 
    "Chrysler", 
    "Citroën", 
    "Cupra", 
    "Dacia", 
    "Daewoo", 
    "Daihatsu", 
    "Dodge", 
    "DS Automobiles", 
    "Ferrari", 
    "Fiat", 
    "Ford",
    "Geely", 
    "Honda", 
    "Hyundai", 
    "Ikco", 
    "Infiniti", 
    "Jaguar", 
    "Kia", 
    "Lada", 
    "Lamborghini",
    "Lancia", 
    "Leapmotor", 
    "Lexus", 
    "Lincoln", 
    "Lotus", 
    "Marcos", 
    "Maserati", 
    "Mazda", 
    "McLaren", 
    "Mercedes-Benz", 
    "MG", 
    "Mini", 
    "Mitsubishi", 
    "Moskwitsch",
    "Nissan",
    "Opel", 
    "Peugeot", 
    "Plymouth", 
    "Polestar", 
    "Pontiac", 
    "Porsche", 
    "Proton", 
    "Rainwoll", 
    "Regal Raptor", 
    "Renault", 
    "RKS", 
    "Rolls-Royce", 
    "Rover", 
    "Saab", 
    "Seat", 
    "Skoda", 
    "Smart", 
    "Subaru", 
    "Suzuki", 
    "Tata", 
    "Tesla", 
    "Tofaş", 
    "Toyota", 
    "Vanderhall", 
    "Volkswagen",
    "Volta", 
    "Volvo", 
    "XEV", 
    "Yuki" 
  ];



  var motor_gucu_otomobil = 
[    
     ["S"] ,
     ["Giulia","Giulia Quadrifoglio","Giulietta","145", "146","147","155","156","159","164","166","33","Brera" ] ,          
     ["A","SV" ] ,  
     ["AR-EV","S1" ] , 
     ["DB11", "DB7","DB9", "DBS Rapide", "Vanquish", "Vantage", "Virage" ] , 
     ["A1","A3","A4","A5","A6","A7","A8","E-Tron GT","R8","RS","S Serisi","TT","TTS" ] , 
     ["Continental","Flying Spur" ] , 
     ["1 Serisi","2 Serisi","3 Serisi","4 Serisi","5 Serisi","6 Serisi","7 Serisi","8 Serisi","i Serisi","M Serisi","Z Serisi"] , 
     ["Chiron" ] , 
     ["Century", "Le Sabre" ,"Park Avenue", "Regal", "Riviera", "Skylark" ] , 
     ["CTS","BLS","Brougham","DeVille","Eldorado","Fleetwood","Seville","STS" ] , 
     ["Alia", "Chance", "Kimo", "Niche" ] , 
     ["Aveo","Camaro","Caprice","Celebrity","Corsica","Corvette","Cruze","Epica","Evanda","Impala","Kalos","Lacetti","Malibu" ] , 
     ["300 C","300 M","Concorde","Crossfire","LHS","Neon","PT Cruiser","Sebring","Stratus" ] , 
     ["AMI","C-Elysée","C1","C2","C3","C3 Picasso","C4","C4 Grand Picasso","C4 Picasso","C4 X","e-C4", "e-C4 X","C5"] , 
     ["Leon" ] , 
     ["Jogger","Lodgy","Logan","Sandero","Solenza" ] , 
     ["Nexia","Nubira","Espero","Lanos","Leganza","Matiz","Racer","Super Saloon","Tico" ] , 
     ["Cuore","Materia","Move","Sirion","Applause","Charade","Copen","YRV" ] , 
     ["Avenger","Challenger","Charger","Magnum","Spirit" ] , 
     ["DS 3","DS 4","DS 5","DS 9" ] , 
     ["296","360","430","458","488","575","599","612","California","F12","F355","F50","F8" ] , 
     ["124 Spider","Albea","Brava","Bravo","126 Bis","Coupe","Croma","500 Ailesi","Egea","Idea","Linea","Marea","Multipla"] , 
     ["B-Max","C-Max","Escort","Fiesta","Focus","Fusion","Galaxy","Grand C-Max","Ka","Mondeo","Mustang","S-Max","Taurus" ] ,
     ["Echo","Emgrand","Familia","FC" ] , 
     ["Accord","City","Civic","Concerto","CR-Z","CRX","E","Integra","Jazz","Legend","Prelude","S2000","Shuttle"] , 
     ["Accent","Accent Blue","Accent Era","Atos","Coupe","Elantra","Excel","Genesis","Getz","Grandeur","i10","i20","i20 Active" ] , 
     ["Samand" ] , 
     ["Q30","Q40","Q50","Q60","G","I30","M"] , 
     ["Daimler","F-Type","S-Type","Sovereign","X-Type","XE","XF","XJ","XJR","XJS","XK8","XKR"] , 
     ["Capital","Carens","Carnival","Ceed","Cerato","Clarus","Magentis","Opirus","Optima","Picanto","Pride","Pro Ceed","Rio"] , 
     ["Kalina","Nova","Priora","Samara","VAZ","Vega" ] , 
     ["Aventador","Diablo","Gallardo","Huracan"] ,
     ["Delta","Thema","Y(Ypsilon)" ] , 
     ["T03" ] , 
     ["CT","ES","GS","IS","LC","LS" ] , 
     ["MKS","Continental","Mark","MKZ","Town Car"] ,  
     ["Elise","Evora","Esprit" ] , 
     ["Mantis" ] , 
     ["Cambiocorsa","Ghibli","GranCabrio","GranTurismo","GT","MC20","Quattroporte","4 Serisi" ] , 
     ["2","3","5","6","MPV","MX","Premacy","121","323","626","929","Lantis","RX" ] , 
     ["720S","Artura","GT","MP4-12C" ] , 
     ["A Serisi","AMG GT","B Serisi","C Serisi","CL","CLA","CLC","CLK","CLS","E Serisi","EQE","EQS","Maybach S" ] , 
     ["F","MG4","ZS" ] , 
     ["Cooper","Cooper Clubman","Cooper Electric","John Cooper","One","Cooper S" ] , 
     ["Attrage","Colt","Galant","Lancer","Lancer Evolution","3000GT","Carisma","Eclipse","Sigma","Space Star","Space Wagon" ] , 
     ["Aleko"] , 
     ["200 SX","350 Z","Almera","Altima","Bluebird","Cefiro","GT-R","Laurel Altima","Maxima","Micra","Note","NX Coupe","Primera"] ,
     ["Adam","Agila","Ascona","Astra","Calibra","Cascada","Corsa","Corsa-e","GT (Roadster)","Insignia","Kadett","Manta","Meriva" ] , 
     ["106","107","205","206","206+","207","208","301","305","306","307","308","309" ] , 
     ["Laser" ] , 
     ["Polestar 2 Long Range" ] , 
     ["Firebird","Grand Prix","Solstice","Sunbird" ] , 
     ["718","911","928","Boxster","Cayman","Panamera","Taycan" ] , 
     ["Gen-2","Saga","Savvy","Waja","315","413","415","416","418","420","Persona" ] , 
     ["RW 10","RW 20" ] , 
     ["K4","K5","K5","Long","M1"] , 
     ["Clio","Espace","Fluence","Fluence Z.E.","Grand Espace","Grand Scenic","Laguna","Latitude","Megane","Modus","Safrane","Scenic","Symbol" ] , 
     ["A1","D2","M5","R3" ] , 
     ["Dawn","Ghost","Wraith" ] , 
     ["25","45","75","200","214","216","218","220","414","416","420","620","820" ] , 
     ["9-3","9-5","900","9000" ] , 
     ["Alhambra","Altea","Arosa","Cordoba","Exeo","Ibiza","Leon","Marbella","Toledo" ] , 
     ["Citigo","Fabia","Favorit","Felicia","Forman","Octavia","Rapid","Roomster","Scala","Superb" ] , 
     ["Fortwo","Forfour","Roadster" ] , 
     ["BRZ","Impreza","Legacy","Levorg","Justy","Vivio" ] , 
     ["Alto","Baleno","Reno","Splash","Swift","SX4","Wagon R","Liana","Maruti" ] , 
     ["Indica","Indigo","Marina","Vista","Manza"] , 
     ["Model 3","Model S","Model X","Model Y" ] , 
     ["Doğan","Kartal","Murat","Şahin","Serçe" ] , 
     ["Auris","Avensis","Avolon","Aygo","Camry","Carina","Celica","Corolla","Corona","Cressida","GT86","Mark 2","MR2" ] , 
     ["Carmel GTS" ] , 
     ["Arteon","Beetle","Bora","Corrado","EOS","Golf","ID.3","Jetta","Lupo","Passat","Passat Alltrack","Passat Variant","Phaeton" ] ,
     ["EV1" ] , 
      ["C30","C70","S40","S60","S70","S80","S90","V40","V40 Cross Country","V50","V60","V60 Cross Country","V70" ] , 
     ["Yoyo" ] , 
    ["Amy" ] 
];




kategoriler[0]["markalar"].push([otomobil_list]);

//localStorage.setItem("kategoriler",JSON.stringify(kategoriler));

//var vites_turleri = ["OTOMATİK","YARI OTOMATİK","MANUEL"]


